Feature/assets 202 search flow
swisstopo/swissgeol-assets-suite pull request #209
Opened 2024-07-10 08:00 UTC by TIL-EBP

resolves #202

2024-07-10 08:35 UTC, daniel-va requested changes

2024-07-10 08:35 UTC, daniel-va commented on apps/client-asset-sg/src/app/i18n/de.ts
>      closeInstructions: 'Anleitung schliessen',
Squash commits.

2024-07-10 08:35 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.scss
>  .loading-spinner {
This class is not used anymore and can be removed.

2024-07-10 08:35 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
> +  public loadingState$ = this._store.select(selectSearchLoadingState);
A couple of these instance variables are no longer in use and can be removed.

2024-07-10 08:35 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.scss
> +  display: grid;
No reason to make this a grid, this can just be a `block`.

+ remove the duplicate `position: relative;` from the `:host` selector (line 4).

2024-07-10 08:35 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
> +  public detailLoadingState$ = this._store.select(selectAssetDetailLoadingState);
Combine these with `combineLatest` and `pipe(map(...))` into something like `isLoading$`. This way, we only need one instance variable for them + It cleans up the template.

2024-07-10 08:35 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
>    private _ngZone = inject(NgZone);
The `closeInstructions$` instance variable can be removed.

2024-07-11 14:54 UTC, vej-ananas commented on libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
> +  @ViewChild('scrollContainer') scrollContainer!: ElementRef;
Make this nullable and handle it below as such - an error occurs otherwise

2024-07-11 14:54 UTC, vej-ananas commented on libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
> +  size = 0;
annotate as public or private

2024-07-11 14:54 UTC, vej-ananas commented on libs/asset-viewer/src/lib/components/asset-search-results/asset-search-results.component.ts
> +  private readonly subscriptions: Subscription = new Subscription();
Im a fan of being consistent - you can mark all the rest as readonly as well :)

2024-07-11 14:54 UTC, vej-ananas commented on libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
> +    map(
No need for a pipe.map, there is a result selector convenience function in combinelatest:
```
  public isLoading$ = combineLatest([
    this._store.select(selectIsMapInitialized),
    this._store.select(selectFilterLoadingState),
    this._store.select(selectSearchLoadingState),
    this._store.select(selectAssetDetailLoadingState),
  ], (isMapInitialized, filterLoadingState, searchLoadingState, detailLoadingState) =>
    !isMapInitialized ||
    filterLoadingState === LoadingState.Loading ||
    searchLoadingState === LoadingState.Loading ||
    detailLoadingState === LoadingState.Loading );
```

2024-07-11 14:54 UTC, vej-ananas commented on libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
> +  protected readonly LoadingState = LoadingState;
Unused

2024-07-15 12:38 UTC, vej-ananas approved these changes

2024-07-15 14:11 UTC, merged