Feature 293: Delete Assets
swisstopo/swissgeol-assets-suite pull request #319
Opened 2024-10-25 07:14 UTC by TIL-EBP

resolves #293

2024-10-28 08:05 UTC, daniel-va requested changes

2024-10-28 13:12 UTC, TIL-EBP commented on libs/persistence/prisma/migrations/20241024140253_delete_asset_cascade/migration.sql
I have removed everything that can be reomved. The remaining deleteions are still required  (I think).

2024-10-29 10:01 UTC, daniel-va requested changes

2024-10-30 17:50 UTC, daniel-va approved these changes

2024-10-30 17:51 UTC, daniel-va commented
Squash Commits before Merge.

2024-11-06 14:53 UTC, merged