Feature 19: Favoriten | Erstellung & Verwaltung
swisstopo/swissgeol-assets-suite pull request #322
Opened 2024-10-29 14:04 UTC by daniel-va

Resolves #19.

2024-11-06 11:07 UTC, TIL-EBP requested changes
A couple remarks: 
- Initially, when moving to the favorites page, i get a internal server error. 
- When moving back to the main filter page, the favoritesONly is still selected, search should be trigered again. 
- - Filters reset when switching between pages (this is for MArcel to decide whether we want to keep them)
- The stats endpoint gives me a lot of errors, but not in all configurations. When i select my test workgroup, i get an internal server error. When i reload the page, there are no more stats. MAybe we can look a t this together

2024-11-06 15:57 UTC, daniel-va commented on libs/asset-viewer/src/lib/components/map/map.component.ts
> +          this.controller.resetZoom();
This should only trigger when the search is reset to its default state, i.e. when the search does not have any results. `hasDefaultFilters` is `true` if and only if there are no active filters.

2024-11-06 16:03 UTC, daniel-va commented on libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
> +  query: {},
It is equivalent, shorter and does not need to be updated whenever we change the query interface.

In JS, when reading the key of an object, and that key does not exist, `undefined` is returned. This is the same as if we set the key to `undefined` manually. There are some slight differences (such as as the behavior of `in` or `Object.keys`), but they don't apply here, as we treat missing and `undefined` query filters the same.

2024-11-07 06:32 UTC, TIL-EBP approved these changes

2024-11-07 12:36 UTC, merged